services:
  mysql:
    image: mysql:8.0
    container_name: swoole_mysql
    restart: unless-stopped
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    networks:
      - new-swoole-network

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/app:delegated
    depends_on:
      - mysql
    networks:
      - new-swoole-network
    environment:
      - OTEL_SERVICE_NAME=swoole-php-app
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_PHP_DISABLED_INSTRUMENTATIONS=all

  web:
    image: nginx:latest
    ports:
      - "9300:80"
    volumes:
      - ./src:/app:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
    networks:
      - new-swoole-network

  jaeger:
    image: jaegertracing/jaeger:2.7.0
    ports:
      - "16690:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - new-swoole-network



networks:
  new-swoole-network:
    driver: bridge

volumes:
  mysql_data: