services:
  influxdb:
    image: influxdb:1.8
    container_name: k6_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - k6_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: k6_grafana
    ports:
      - "3000:3000" # json
      - "3001:3001" # jaeger
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - k6_network
    depends_on:
      - influxdb

networks:
  k6_network:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data: 