services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mysql
    networks:
      - new-nginx-network
    environment:
      - OTEL_SERVICE_NAME=nginx-fpm-app
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_PHP_DISABLED_INSTRUMENTATIONS=all
  web:
    image: nginx:latest
    ports:
      - "9200:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - new-nginx-network

  jaeger:
    image: jaegertracing/jaeger:2.7.0
    ports:
      - "16689:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - new-nginx-network

  mysql:
    image: mysql:8.0
    container_name: nginx_mysql
    restart: unless-stopped
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    networks:
      - new-nginx-network

networks:
  new-nginx-network:
    driver: bridge

volumes:
  mysql_data: